/*
 * gestion de la vue (SWING)
 *  
 * Author : Adeline, Christophe, Cyril, Christine
 */
package vue;

import controller.FormController;
import model.Address;
import response.CustomResponse;
import response.FormatErrorEnum;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author stag
 */
public class InterfaceCarnet extends javax.swing.JFrame {

    private FormController controller;
    private List<Address> addresses = new ArrayList<>();

    /**
     * Creates new form Interface_Carnet
     */
    public InterfaceCarnet() {

        //création de l'objet controller qui va servir à demander la création du crud
        controller = new FormController();

        // création vue
        initComponents();
        raz_zones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        intTelMobile = new javax.swing.JTextField();
        txtMailPerso = new javax.swing.JTextField();
        txtAppartBat = new javax.swing.JTextField();
        intNumeroVoie = new javax.swing.JTextField();
        txtLibelleVoie = new javax.swing.JTextField();
        intCodePostal = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        boutonCiviliteMonsieur = new javax.swing.JRadioButton();
        boutonCiviliteMadame = new javax.swing.JRadioButton();
        boutonCiviliteSociete = new javax.swing.JRadioButton();
        txtComplementNumeroVoie = new javax.swing.JTextField();
        intTelFixe = new javax.swing.JTextField();
        txtMailPro = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnenr = new javax.swing.JButton();
        btnan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        hiddenButton = new javax.swing.JRadioButton();
        txtId = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtCiv = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(475, 670));

        txtNom.setBackground(new java.awt.Color(238, 238, 238));
        txtNom.setBorder(null);
        txtNom.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        txtNom.setMinimumSize(new java.awt.Dimension(4, 10));
        txtNom.setName(""); // NOI18N
        txtNom.setPreferredSize(new java.awt.Dimension(4, 100));
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        txtPrenom.setBackground(new java.awt.Color(238, 238, 238));
        txtPrenom.setBorder(null);
        txtPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrenomActionPerformed(evt);
            }
        });

        intTelMobile.setBackground(new java.awt.Color(238, 238, 238));
        intTelMobile.setBorder(null);
        intTelMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intTelMobileActionPerformed(evt);
            }
        });

        txtMailPerso.setBackground(new java.awt.Color(238, 238, 238));
        txtMailPerso.setBorder(null);

        txtAppartBat.setBackground(new java.awt.Color(238, 238, 238));
        txtAppartBat.setBorder(null);

        intNumeroVoie.setBackground(new java.awt.Color(238, 238, 238));
        intNumeroVoie.setBorder(null);
        intNumeroVoie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intNumeroVoieActionPerformed(evt);
            }
        });

        txtLibelleVoie.setBackground(new java.awt.Color(238, 238, 238));
        txtLibelleVoie.setBorder(null);
        txtLibelleVoie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibelleVoieActionPerformed(evt);
            }
        });

        intCodePostal.setBackground(new java.awt.Color(238, 238, 238));
        intCodePostal.setBorder(null);

        txtVille.setBackground(new java.awt.Color(238, 238, 238));
        txtVille.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("M.");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Mme");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Société");

        boutonCiviliteMonsieur.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(boutonCiviliteMonsieur);
        boutonCiviliteMonsieur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCiviliteMonsieurActionPerformed(evt);
            }
        });

        boutonCiviliteMadame.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(boutonCiviliteMadame);
        boutonCiviliteMadame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCiviliteMadameActionPerformed(evt);
            }
        });

        boutonCiviliteSociete.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(boutonCiviliteSociete);
        boutonCiviliteSociete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCiviliteSocieteActionPerformed(evt);
            }
        });

        txtComplementNumeroVoie.setBackground(new java.awt.Color(238, 238, 238));
        txtComplementNumeroVoie.setBorder(null);
        txtComplementNumeroVoie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementNumeroVoieActionPerformed(evt);
            }
        });

        intTelFixe.setBackground(new java.awt.Color(238, 238, 238));
        intTelFixe.setBorder(null);
        intTelFixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intTelFixeActionPerformed(evt);
            }
        });

        txtMailPro.setBackground(new java.awt.Color(238, 238, 238));
        txtMailPro.setBorder(null);
        txtMailPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailProActionPerformed(evt);
            }
        });

        jButton4.setText("Rechercher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnenr.setText("Enregistrer");
        btnenr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenrActionPerformed(evt);
            }
        });

        btnan.setText("Annuler");
        btnan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom*");

        jLabel3.setText("Prénom");

        jLabel4.setText("Appart/Bat");

        jLabel5.setText("N° voie");

        jLabel6.setText("Complément");

        jLabel7.setText("Libelle adresse");

        jLabel8.setText("Code postal");

        jLabel9.setText("Ville");

        jLabel10.setText("Tel. mobile");

        jLabel14.setText("Tel. fixe      ");

        jLabel15.setText("Mail personnel");

        jLabel16.setText("Mail professionnel");

        hiddenButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(hiddenButton);
        hiddenButton.setSelected(true);
        hiddenButton.setMaximumSize(new java.awt.Dimension(0, 0));
        hiddenButton.setMinimumSize(new java.awt.Dimension(0, 0));
        hiddenButton.setPreferredSize(new java.awt.Dimension(0, 0));
        hiddenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiddenButtonActionPerformed(evt);
            }
        });

        txtId.setText("id");
        txtId.setMaximumSize(new java.awt.Dimension(0, 0));
        txtId.setMinimumSize(new java.awt.Dimension(0, 0));
        txtId.setPreferredSize(new java.awt.Dimension(0, 0));
        txtId.setRequestFocusEnabled(false);

        btnUpdate.setText("Mettre à jour");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtCiv.setMaximumSize(new java.awt.Dimension(0, 0));
        txtCiv.setMinimumSize(new java.awt.Dimension(0, 0));
        txtCiv.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel17.setText("* Champ obligatoire ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boutonCiviliteMonsieur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(boutonCiviliteMadame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addComponent(boutonCiviliteSociete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(hiddenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(intTelFixe))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(intTelMobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVille, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMailPerso, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMailPro)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrenom)
                                    .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(268, 268, 268)
                                        .addComponent(txtComplementNumeroVoie))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(txtAppartBat))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(intNumeroVoie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(intCodePostal, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                        .addComponent(txtLibelleVoie))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnenr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(btnan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(boutonCiviliteMadame, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(boutonCiviliteSociete)
                        .addComponent(boutonCiviliteMonsieur, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(hiddenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAppartBat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(intNumeroVoie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtComplementNumeroVoie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLibelleVoie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(intCodePostal, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVille, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(intTelMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(intTelFixe, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMailPerso, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMailPro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnenr)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Carnet d'adresses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // public static void main(String[] args) {
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    /**
     * try { for (javax.swing.UIManager.LookAndFeelInfo info :
     * javax.swing.UIManager.getInstalledLookAndFeels()) { if
     * ("Nimbus".equals(info.getName())) {
     * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } }
     * catch (ClassNotFoundException ex
     * <p>
     * <p>
     * ) {
     * java.util.logging.Logger.getLogger(InterfaceCarnet.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); } catch (InstantiationException ex
     * <p>
     * <p>
     * ) {
     * java.util.logging.Logger.getLogger(InterfaceCarnet.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); } catch (IllegalAccessException ex
     * <p>
     * <p>
     * ) {
     * java.util.logging.Logger.getLogger(InterfaceCarnet.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); } catch (javax.swing.UnsupportedLookAndFeelException ex
     * <p>
     * <p>
     * ) {
     * java.util.logging.Logger.getLogger(InterfaceCarnet.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); }
     */
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //   java.awt.EventQueue.invokeLater(() -> {
    //       new InterfaceCarnet().setVisible(true);
    //   });
    //  }
    // boutton annuler
    /**
     * gestion du bouton annuler
     */
    private void btnanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanActionPerformed
        // RAZ de mes champs
        raz_zones();
    }//GEN-LAST:event_btnanActionPerformed
    /**
     * gestion du bouton enregistrer
     */
    private void btnenrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenrActionPerformed

        // création objet address contenant les champs de la vue
        Address address = new Address();

        // on recupere les champs de la vue dans l'objet address
        if (boutonCiviliteMonsieur.isSelected()) {
            address.setCivilite("M.");
        } else if (boutonCiviliteMadame.isSelected()) {
            address.setCivilite("Mme");
        } else if (boutonCiviliteSociete.isSelected()) {
            address.setCivilite("Société");
        } else {
            address.setCivilite(null);
        }

        address.setNom(txtNom.getText());
        address.setPrenom(txtPrenom.getText().isEmpty() ? null : txtPrenom.getText());
        address.setAppartbat(txtAppartBat.getText());
        address.setNumeroVoie(intNumeroVoie.getText());
        address.setComplementNumeroVoie(txtComplementNumeroVoie.getText());
        address.setLibelleVoie(txtLibelleVoie.getText());
        address.setCodePostal(intCodePostal.getText());
        address.setVille(txtVille.getText());
        address.setTelephoneMobile(intTelMobile.getText());
        address.setTelephoneFixe(intTelFixe.getText());
                address.setMailPerso(txtMailPerso.getText().isEmpty() ? null : txtMailPerso.getText());
        address.setMailPro(txtMailPro.getText().isEmpty() ? null : txtMailPro.getText());

        // je demande au controller de creer l'adresse en lui passant l'objet rempli et je stocke le resultat
        CustomResponse resultat = controller.createAddress(address);

        if (resultat.getResponseCode().equals(FormatErrorEnum.SUCCESS)) {
            // RAZ de mes champs
            raz_zones();

            // popup réussite
            JOptionPane.showMessageDialog(this, "Contact enregistré avec succés.");
        } else {
            // TODO : mettre des champs en rouge
            // TODO;popup 
            resultat.getResponseCode();
            resultat.getErrorMessage();
        }


    }//GEN-LAST:event_btnenrActionPerformed
   /**
     * gestion du bouton Rechercher : /nom /libellé voie /CP /ville
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // création objet address contenant le champs nom libelle voie cp ville
        Address address = new Address();

        // on recupere les champs de la vue dans l'objet address 
        address.setId(txtId.getText());
        address.setNom(txtNom.getText().isEmpty() ? null : txtNom.getText());
        address.setLibelleVoie(txtLibelleVoie.getText().isEmpty() ? null : txtLibelleVoie.getText());
        address.setCodePostal(intCodePostal.getText().isEmpty() ? null : intCodePostal.getText());
        address.setVille(txtVille.getText().isEmpty() ? null : txtVille.getText());

        // je demande au controller de faire le select sur le nom en lui passant l'objet rempli et je stocke le resultat
        CustomResponse resultat = controller.retrieveAddress(address);
        if (txtNom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aucun nom d'entré. Vous avez la liste complète");
        }

        if (resultat.getResponseCode().equals(FormatErrorEnum.SUCCESS)) {
            addresses = resultat.getAddresses();

            // affichage dans tableau
            if (addresses.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pas de contact avec les infos entrées.");
            }
            // Définition du modèle
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("Nom");
            model.addColumn("Prénom");
            model.addColumn("Code postal");
            model.addColumn("Ville");
            for (Address adresse
                    : addresses) {
                model.addRow(new Object[]{
                    adresse.getId(), adresse.getNom(), adresse.getPrenom(), adresse.getCodePostal(), adresse.getVille()});
            }
            // on applique le model à la table
            jTable2.setModel(model);
            // RAZ de mes champs

            // Affichage dans bouton : solution non retenue
            //String req;
            //JFrame frame = new JFrame();
            //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            // frame.setTitle("Fenetre de test");
            // JPanel jPanelREPONSES = new JPanel();
            // frame.add(jPanelREPONSES);
            // jPanelREPONSES.setLayout(new GridLayout(0, 1));
            // int h = 0;
            //for (Address adresse
            //        : addresses) {
            //    model.addRow(new Object[]{
            //        adresse.getNom(), adresse.getPrenom(), adresse.getCodePostal(), adresse.getVille()});
            //    String nomResultat = adresse.getNom() + " " + adresse.getPrenom() + " (" + adresse.getCodePostal() + " " + adresse.getVille() + ")";
            //    System.out.println(nomResultat);
            //    JButton jButtonResultat = new javax.swing.JButton();
            //    jButtonResultat.setText(nomResultat);
            //    jPanelREPONSES.add(jButtonResultat);
            //    jButtonResultat.setVisible(true);
            //    h += 50;
            // }
            // frame.setSize(600, h);
            // jPanelREPONSES.setVisible(true);
            // frame.setVisible(true);
            // raz_zones();
            // popup réussite
            //        JOptionPane.showMessageDialog(this, "Recherche");
        } else {
            // TODO : liste vide : aucune selection
            // TODO;popup 
            resultat.getResponseCode();
            resultat.getErrorMessage();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void intTelMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intTelMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intTelMobileActionPerformed

    private void txtLibelleVoieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibelleVoieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibelleVoieActionPerformed

    private void boutonCiviliteMonsieurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCiviliteMonsieurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonCiviliteMonsieurActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void intNumeroVoieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intNumeroVoieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intNumeroVoieActionPerformed

    private void txtComplementNumeroVoieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementNumeroVoieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementNumeroVoieActionPerformed

    private void intTelFixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intTelFixeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intTelFixeActionPerformed

    private void txtMailProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailProActionPerformed

    private void txtPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrenomActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * gestion du bouton supprimer 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // création objet address contenant les champs de la vue
        Address address = new Address();

        address.setId(txtId.getText());

        // je demande au controller de supprimer l'adresse en lui passant l'objet rempli et je stocke le resultat
        CustomResponse resultat = controller.deleteAddress(address);

        if (resultat.getResponseCode().equals(FormatErrorEnum.SUCCESS)) {
            // RAZ de mes champs
            raz_zones();

            // popup réussite
            JOptionPane.showMessageDialog(this, "Contact supprimé avec succés.");
        } else {
            // TODO : mettre des champs en rouge
            // TODO;popup 
            resultat.getResponseCode();
            resultat.getErrorMessage();
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void boutonCiviliteMadameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCiviliteMadameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonCiviliteMadameActionPerformed

    private void boutonCiviliteSocieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCiviliteSocieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonCiviliteSocieteActionPerformed

    private void hiddenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiddenButtonActionPerformed
        hiddenButton.setVisible(false);
    }//GEN-LAST:event_hiddenButtonActionPerformed
/**
     * gestion du bouton mise à jour 
     */
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // création objet address contenant les champs de la vue
        Address address = new Address();

        // on recupere les champs de la vue dans l'objet address
        if (boutonCiviliteMonsieur.isSelected()) {
            address.setCivilite("M.");
        } else if (boutonCiviliteMadame.isSelected()) {
            address.setCivilite("Mme");
        } else if (boutonCiviliteSociete.isSelected()) {
            address.setCivilite("Société");
        } else {
            address.setCivilite(null);
        }

        address.setId(txtId.getText());
        address.setNom(txtNom.getText());
        address.setPrenom(txtPrenom.getText().isEmpty() ? null : txtPrenom.getText());
        address.setAppartbat(txtAppartBat.getText());
        address.setNumeroVoie(intNumeroVoie.getText());
        address.setComplementNumeroVoie(txtComplementNumeroVoie.getText());
        address.setLibelleVoie(txtLibelleVoie.getText());
        address.setCodePostal(intCodePostal.getText());
        address.setVille(txtVille.getText());
        address.setTelephoneMobile(intTelMobile.getText());
        address.setTelephoneFixe(intTelFixe.getText());
        address.setMailPerso(txtMailPerso.getText());
        address.setMailPro(txtMailPro.getText());

        // je demande au controller de creer l'adresse en lui passant l'objet rempli et je stocke le resultat
        CustomResponse resultat = controller.updateAddress(address);

        if (resultat.getResponseCode().equals(FormatErrorEnum.SUCCESS)) {
            // RAZ de mes champs
            raz_zones();

            // popup réussite
            JOptionPane.showMessageDialog(this, "Contact mis à jour avec succès.");
        } else {
            // TODO : mettre des champs en rouge
            // TODO;popup 
            resultat.getResponseCode();
            resultat.getErrorMessage();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseClicked

    /**
     * Sélection dans liste résultat recherche pour affichage contact dans formulaire 
     */
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        Map<String, Address> addresseMap = addresses.stream().collect(Collectors.toMap(Address::getId, adrs -> adrs));

        int ligne = jTable2.rowAtPoint(evt.getPoint());
        //        addresses.get(ligne);
        String id = (String) jTable2.getModel().getValueAt(ligne, 0);

        Address clickedAddress = addresseMap.get(id);

        txtCiv.setText(clickedAddress.getCivilite());
        boutonCiviliteMonsieur.setSelected(true);
        if (txtCiv.getText().equals("Mme")) {
            boutonCiviliteMadame.setSelected(true);
        } else if (txtCiv.getText().equals("Société")) {
            boutonCiviliteSociete.setSelected(true);
        }
        txtId.setText(clickedAddress.getId());
        txtNom.setText(clickedAddress.getNom());
        txtPrenom.setText(clickedAddress.getPrenom());
        intTelMobile.setText(clickedAddress.getTelephoneMobile());
        txtMailPerso.setText(clickedAddress.getMailPerso());
        txtAppartBat.setText(clickedAddress.getAppartbat());
        txtComplementNumeroVoie.setText(clickedAddress.getComplementNumeroVoie());
        txtLibelleVoie.setText(clickedAddress.getLibelleVoie());
        txtMailPro.setText(clickedAddress.getMailPro());
        txtVille.setText(clickedAddress.getVille());
        intCodePostal.setText(clickedAddress.getCodePostal());
        intNumeroVoie.setText(clickedAddress.getNumeroVoie());
        intTelFixe.setText(clickedAddress.getTelephoneFixe());
        //hiddenButton.setSelected(true);

    }//GEN-LAST:event_jTable2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boutonCiviliteMadame;
    private javax.swing.JRadioButton boutonCiviliteMonsieur;
    private javax.swing.JRadioButton boutonCiviliteSociete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnan;
    private javax.swing.JButton btnenr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton hiddenButton;
    private javax.swing.JTextField intCodePostal;
    private javax.swing.JTextField intNumeroVoie;
    private javax.swing.JTextField intTelFixe;
    private javax.swing.JTextField intTelMobile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtAppartBat;
    private javax.swing.JTextField txtCiv;
    private javax.swing.JTextField txtComplementNumeroVoie;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLibelleVoie;
    private javax.swing.JTextField txtMailPerso;
    private javax.swing.JTextField txtMailPro;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables

    /**
     * gestion effacement zone formualaire, réinitialise bouton et vide liste resultat recherche
     */
    private void raz_zones() {

        txtId.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        intTelMobile.setText("");
        txtMailPerso.setText("");
        txtAppartBat.setText("");
        txtComplementNumeroVoie.setText("");
        txtLibelleVoie.setText("");
        txtMailPro.setText("");
        txtVille.setText("");
        intCodePostal.setText("");
        intNumeroVoie.setText("");
        intTelFixe.setText("");
        hiddenButton.setSelected(true);

        // RAZ tableau recherche
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nom");
        model.addColumn("Prénom");
        model.addColumn("Code postal");
        model.addColumn("Ville");
        jTable2.setModel(model);

    }

}
